export const organizationData = [
  {
    id: 1,
    propertyId: 1,
    organizationName: 'JNC Group',
    orgState: 'Public Limited Company',
    contactNo: 674565834,
    email: 'dasdg@gmail.com',
    websiteUrl: 'www.jnc.com',
    industry: 'Construction',
    strength: 22,
    verticals: ['Property management', 'Commercial leasing', 'management', 'leasing'],
    propertyEngagement: 'On Lease',
    nearestAddress: 'Balewadi Pune - 411045',
    headOffice: 'Balewadi Pune - 411045',
    description:
      "The point of using Lorem Ipsum is that it has a more-or- less normal distribution of letters, as opposed to using 'Content here, content",
    foundedYear: 2005,
    directors: [
      {
        name: 'Nishant Dabbas',
        contactNo: 674565834,
        email: 'Nishant.dabbas@jncgroup.com',
      },
    ],
    organizationImgURL: 'jnc.png',
    isVerified: true,
    rating: 3.5,
    showDates: false,
    showDirectorInfo: true,
    startDate: '02-12-1996',
    endDate: '02-05-2001',
  },
  {
    id: 2,
    propertyId: 1,
    organizationName: 'Hillside Pancard Group',
    orgState: 'Public Limited Company',
    contactNo: 674565834,
    email: 'dasdg@gmail.com',
    websiteUrl: 'www.jnc.com',
    industry: 'Construction',
    strength: 22,
    verticals: ['management', 'leasing'],
    propertyEngagement: 'On Lease',
    nearestAddress: 'Balewadi Pune - 411045',
    headOffice: 'Balewadi Pune - 411045',
    description: 'fds fsd fsdag rey rtgh rdfsge sdg trh rth rtey h',
    foundedYear: 2005,
    directors: [
      {
        name: 'Nishant Dabbas',
        contactNo: 674565834,
        email: 'Nishant.dabbas@jncgroup.com',
      },
    ],
    organizationImgURL: 'propert1.png',
    isVerified: true,
    rating: 0,
    showDates: false,
    showDirectorInfo: false,
    startDate: '12-01-1991',
    endDate: '',
  },
  {
    id: 3,
    propertyId: 1,
    organizationName: 'XYZ Group',
    orgState: 'Public Limited Company',
    contactNo: 674565834,
    email: 'dasdg@gmail.com',
    websiteUrl: 'www.jnc.com',
    industry: 'Construction',
    strength: 22,
    verticals: ['management', 'leasing'],
    propertyEngagement: 'On Lease',
    nearestAddress: 'Balewadi Pune - 411045',
    headOffice: 'Balewadi Pune - 411045',
    description: 'fds fsd fsdag rey rtgh rdfsge sdg trh rth rtey h',
    foundedYear: 2005,
    directors: null,
    organizationImgURL: '',
    isVerified: true,
    rating: 5.0,
    showDates: true,
    showDirectorInfo: true,
    startDate: '02-12-1996',
    endDate: '02-05-2001',
  },
  {
    id: 4,
    propertyId: 1,
    organizationName: 'QWE Group',
    orgState: 'Public Limited Company',
    contactNo: 674565834,
    email: 'dasdg@gmail.com',
    websiteUrl: 'www.jnc.com',
    industry: 'Construction',
    strength: 22,
    verticals: ['management', 'leasing'],
    propertyEngagement: 'On Lease',
    nearestAddress: 'Balewadi Pune - 411045',
    headOffice: 'Balewadi Pune - 411045',
    description: 'fds fsd fsdag rey rtgh rdfsge sdg trh rth rtey h',
    foundedYear: 2005,
    directors: [],
    organizationImgURL: 'jnc.png',
    isVerified: false,
    rating: 3.0,
    showDates: true,
    showDirectorInfo: true,
    startDate: '',
    endDate: '02-05-2001',
  },
];
