export const propertyData = [
  {
    propertyName: "yrtyr",
    area: "Aundh",
    developerName: "John",
    contactNo: 3168146858,
    email: "ashwin@gmail.com",
    location: "gcskdhjgf csdhcksd csdh",
    amenities: ["Play Area", "Gym", "Gym"],
    areaFacilities: { Hospital: "2.5 KM", School: "2.5 KM" },
  },
  {
    propertyName: "mbnvyg",
    area: "Kothrud",
    developerName: "Emily",
    contactNo: 9003761618,
    email: "ashwin@gmail.com",
    location: "gcskdhjgf csdhcksd csdh",
    amenities: ["Gym", "Club House", "Club House"],
    areaFacilities: { Hospital: "1.0 KM", School: "2.4 KM" },
  },
  {
    propertyName: "hgfhf",
    area: "Wakad",
    developerName: "John",
    contactNo: 6902457581,
    email: "ashwin@gmail.com",
    location: "gcskdhjgf csdhcksd csdh",
    amenities: ["Club House", "Club House", "Club House"],
    areaFacilities: { Hospital: "0.5 KM", School: "3.1 KM" },
  },
  {
    propertyName: "hgfhf",
    area: "Kothrud",
    developerName: "John",
    contactNo: 6188096174,
    email: "ashwin@gmail.com",
    location: "gcskdhjgf csdhcksd csdh",
    amenities: ["Play Area", "Garden"],
    areaFacilities: { Hospital: "4.2 KM", School: "8.2 KM" },
  },
  {
    propertyName: "hgfhf",
    area: "Wakad",
    developerName: "Alice",
    contactNo: 3559527790,
    email: "ashwin@gmail.com",
    location: "gcskdhjgf csdhcksd csdh",
    amenities: ["Gym", "Club House", "Club House"],
    areaFacilities: { Hospital: "3.7 KM", School: "7.0 KM" },
  },
];
