export const keySkills = [
  'Market Analysis',
  'Salesmanship',
  'Customer Service',
  'Marketing',
  'Property Management',
  'Financial Analysis',
  'Legal Knowledge',
  'Networking',
  'Technology Proficiency',
  'Problem-solving',
  'Time Management',
  'Attention to Detail',
  'Emotional Intelligence',
  'Adaptability',
  'Ethics and Integrity',
];

export const buyOptions = [
  'IT Hardware and Software',
  'Office Furniture and Equipment',
  'Telecommunications Equipment',
  'Security Systems',
  'Financial Software and Systems',
  'Office Supplies',
  'Data Storage Solutions',
  'Training and Development',
  'Marketing and Advertising',
  'Consulting Services',
  'Insurance Services',
  'Real Estate',
  'Travel and Entertainment',
  'Human Resources Services',
  'Research and Development',
  'Supply Chain Management',
  'Legal and Regulatory Compliance',
  'Customer Relationship Management (CRM)',
  'Health and Safety Equipment',
  'Utilities and Facilities Management',
];

export const sellOptions = [
  'Broker- Commercial real estate Consulting',
  'Broker- Residential Real estate Consulting',
  'Broker-All Type of real estate consulting including Ware house, Factory premises etc',
  'Buyer- Purchase of Residential property',
  'Buyer- Purchase of comercial property',
  'Buyer- Investment opportunities',
  "Seller- 'I am interested to sell' my commercial property/s",
  "Seller- 'I am here to sell' my residential property/s",
  "Seller - 'I am interested to sell' both residential and commercial property/s",
  'Co-working Operator- Intersted in - Sourcing property/s',
  'Co-working Operator- Intersted in - Selling Seats/ Cabins/ Enterprises managed office deals',
  'Co-Working Operator- Intersted in-Streamlining Processes and Sell faster',
];

export const targetAudience = [
  'IT /ITES companies',
  'BPO/KPO',
  'Consulting businesses',
  'Banking, Financial Services, and Insurance (BFSI)',
  'Telecommunications',
  'Consulting and Professional Services',
  'E-commerce and Technology Startups',
  'Manufacturing and Industrial',
  'Real Estate and Construction',
  'Healthcare and Pharmaceuticals',
  'Retail and Consumer Goods',
  'Government and Public Sector',
];

export const dreamClients = [
  'Tata Consultancy Services (TCS)',
  'Infosys Limited',
  'Wipro Limited',
  'HCL Technologies',
  'Tech Mahindra',
  'Cognizant Technology Solutions',
  'Accenture',
  'IBM India',
  'Capgemini',
  'Larsen & Toubro Infotech (LTI)',
  'State Bank of India (SBI)',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'Bajaj Finance',
  'HDFC Life Insurance',
  'Life Insurance Corporation of India (LIC)',
  'Birla Sun Life Insurance',
  'SBI Life Insurance',
  'Bharti Airtel',
  'Reliance Jio',
  'Vodafone Idea Limited',
  'BSNL (Bharat Sanchar Nigam Limited)',
  'Tata Communications',
  'Idea Cellular',
  'Aircel',
  'MTNL (Mahanagar Telephone Nigam Limited)',
  'Reliance Communications',
  'Tata Teleservices',
  'McKinsey & Company',
  'Boston Consulting Group (BCG)',
  'Bain & Company',
  'Deloitte',
  'PricewaterhouseCoopers (PwC)',
  'Ernst & Young (EY)',
  'KPMG',
  'Accenture Consulting',
  'Capgemini Consulting',
  'Booz Allen Hamilton',
  'Amazon India',
  'Flipkart',
  'Paytm',
  'Ola Cabs',
  'Swiggy',
  'Zomato',
  "Byju's",
  'MakeMyTrip',
  'OYO Rooms',
  'Policybazaar',
  'Tata Steel',
  'Reliance Industries Limited (RIL)',
  'Mahindra & Mahindra',
  'Larsen & Toubro (L&T)',
  'Bharat Heavy Electricals Limited (BHEL)',
  'Hindustan Unilever Limited (HUL)',
  'Maruti Suzuki India Limited',
  'Hero MotoCorp',
  'Siemens India',
  'Aditya Birla Group',
  'DLF Limited',
  'Godrej Properties Limited',
  'Oberoi Realty Limited',
  'Prestige Group',
  'Brigade Group',
  'Sobha Limited',
  'Tata Housing Development Company Limited',
  'Mahindra Lifespace Developers Limited',
  'Lodha Group',
  'Hiranandani Developers',
  'Sun Pharmaceutical Industries Limited',
  "Dr. Reddy's Laboratories",
  'Cipla Limited',
  'Lupin Limited',
  'Aurobindo Pharma',
  'Biocon Limited',
  'Cadila Healthcare',
  'GlaxoSmithKline Pharmaceuticals Limited (GSK)',
  'Apollo Hospitals',
  'Fortis Healthcare',
  'Reliance Retail',
  'Future Group',
  'Aditya Birla Fashion and Retail Limited',
  'Avenue Supermarts (D-Mart)',
  'Titan Company Limited',
  'ITC Limited (FMCG Division)',
  'Hindustan Unilever Limited (HUL)',
  'Patanjali Ayurved Limited',
  'BigBasket',
  "Spencer's Retail",
  'Bharat Electronics Limited (BEL)',
  'Indian Oil Corporation Limited (IOCL)',
  'Bharat Heavy Electricals Limited (BHEL)',
  'State Bank of India (SBI)',
  'Life Insurance Corporation of India (LIC)',
  'Air India',
  'National Thermal Power Corporation Limited (NTPC)',
  'Indian Railways',
  'Oil and Natural Gas Corporation Limited (ONGC)',
  'Bharat Sanchar Nigam Limited (BSNL)',
];

export const interests = [
  'Reading',
  'Writing',
  'Cooking and baking',
  'Hiking and nature exploration',
  'Painting or drawing',
  'Photography',
  'Playing musical instruments',
  'Traveling',
  'Yoga and meditation',
  'Gardening',
  'DIY crafts ',
  'Gaming',
  'Fitness and exercise',
  'Astronomy and stargazing',
  'Learning new languages',
  'Volunteer work and community service',
  'Film and cinema appreciation',
  'History and historical reenactment',
  'Fashion and styling',
  'Podcasting and content creation',
  'Music appreciation (e.g., concerts, music festivals)',
  'Philosophy and deep conversations',
  'Scuba diving and snorkeling',
  'Sustainable living and environmental activism',
  'Collecting',
];
