name: CI/CD Pipeline for trythat-Frontend-rohit

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/trythat-frontend-rohit:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/trythat-frontend-rohit:latest

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH Key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/id_rsa
          chmod 400 /tmp/id_rsa

      - name: SSH into EC2 and Deploy Docker Container
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Stop and remove the existing container (if running)
            sudo docker stop trythat-frontend-rohit || true
            sudo docker rm trythat-frontend-rohit || true

            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/trythat-frontend-rohit:latest

            # Run the Docker container
            sudo docker run -d -p 80:80 --name trythat-frontend-rohit ${{ secrets.DOCKER_USERNAME }}/trythat-frontend-rohit:latest

            # Cleanup unused Docker resources
            sudo docker system prune -f
          EOF
