name: Build, Test, and Deploy with SonarCloud
#
on:
  push:
    branches:
      - main
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Store your SonarCloud token in GitHub Secrets
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=rohitsoni1209_trythat-Frontend-rohit \
            -Dsonar.organization=rohitsoni1209 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -X

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/trythat-frontend-rohit:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/trythat-frontend-rohit:latest

      - name: Deploy on EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Write the SSH key to a file
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

          # SSH into the EC2 instance and deploy the Docker container
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Stop and remove the existing container (if running)
            sudo docker stop trythat-frontend-rohit || true
            sudo docker rm trythat-frontend-rohit || true

            # Pull the latest Docker image
            sudo docker pull $DOCKER_USERNAME/trythat-frontend-rohit:latest

            # Run the Docker container
            sudo docker run -d -p 80:80 --name trythat-frontend-rohit $DOCKER_USERNAME/trythat-frontend-rohit:latest

            # Cleanup unused Docker resources
            sudo docker system prune -f
          EOF

          # Remove the SSH key for security
          rm -f /tmp/id_rsa
